This Notebook contains the code for training and measuring training time, inference time of the XGB, Naive Bayes. They are evaluated over dataset of various sizes like 3.5M,350k,35000 rows. These are evaluated after feature selection.

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import plotly.graph_objects as go
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, confusion_matrix, ConfusionMatrixDisplay, classification_report,roc_curve

import xgboost as xgb
from sklearn.model_selection import GridSearchCV

from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.multiclass import OneVsOneClassifier
import time
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv("iot23_final_preprocessed.csv")

In [4]:
df.head()

Unnamed: 0  duration  orig_bytes  resp_bytes  orig_pkts  resp_pkts  \
0          20  0.000061         0.0         0.0        3.0        0.0   
1          21  0.000000         0.0         0.0        1.0        0.0   
2          23  0.000061         0.0         0.0        3.0        0.0   
3          24  0.000000         0.0         0.0        1.0        0.0   
4          27  0.000000         0.0         0.0        1.0        0.0   

                       label  proto_tcp  proto_udp  conn_state_REJ  ...  \
0  PartOfAHorizontalPortScan        1.0        0.0             0.0  ...   
1  PartOfAHorizontalPortScan        1.0        0.0             0.0  ...   
2  PartOfAHorizontalPortScan        1.0        0.0             0.0  ...   
3  PartOfAHorizontalPortScan        1.0        0.0             0.0  ...   
4                     Benign        1.0        0.0             0.0  ...   

   conn_state_S3  conn_state_SF  conn_state_SH  conn_state_SHR  service_dhcp  \
0            0.0            0.0            0.0             0.0           0.0   
1            0.0            0.0            0.0             0.0           0.0   
2            0.0            0.0            0.0             0.0           0.0   
3            0.0            0.0            0.0             0.0           0.0   
4            0.0            0.0            0.0             0.0           0.0   

   service_dns  service_http  service_irc  service_ssh  service_ssl  
0          0.0           0.0          0.0          0.0          0.0  
1          0.0           0.0          0.0          0.0          0.0  
2          0.0           0.0          0.0          0.0          0.0  
3          0.0           0.0          0.0          0.0          0.0  
4          0.0           0.0          0.0          0.0          0.0  

[5 rows x 27 columns]

In [5]:


print(df.columns)

Index(['Unnamed: 0', 'duration', 'orig_bytes', 'resp_bytes', 'orig_pkts',
       'resp_pkts', 'label', 'proto_tcp', 'proto_udp', 'conn_state_REJ',
       'conn_state_RSTO', 'conn_state_RSTOS0', 'conn_state_RSTR',
       'conn_state_RSTRH', 'conn_state_S0', 'conn_state_S1', 'conn_state_S2',
       'conn_state_S3', 'conn_state_SF', 'conn_state_SH', 'conn_state_SHR',
       'service_dhcp', 'service_dns', 'service_http', 'service_irc',
       'service_ssh', 'service_ssl'],
      dtype='object')


In [6]:
df['label'].unique()

array(['PartOfAHorizontalPortScan', 'Benign', 'Okiru', 'DDoS',
       'C&C-HeartBeat', 'C&C', 'Attack'], dtype=object)

In [7]:
df['label'].value_counts()

label
PartOfAHorizontalPortScan    825417
Okiru                        262503
Benign                       197274
DDoS                         138718
C&C                           15003
Attack                         3914
C&C-HeartBeat                   308
Name: count, dtype: int64

In [8]:
df['label'] = df['label'].apply(lambda x: 0 if x == 'Benign' else 1)

In [9]:
y = df['label']
X=df = df.drop(columns=['label', 'Unnamed: 0'])
selected_indexes = [0, 3,6,5,1]  
X_selected = X.iloc[:, selected_indexes]

X_train, X_test, y_train, y_test = train_test_split(
    X_selected, y, test_size=0.25, random_state=69, stratify=y
)


In [10]:
print(X_train)

             duration  orig_pkts  proto_udp  proto_tcp  orig_bytes
1367863  0.000000e+00        1.0        0.0        1.0         0.0
1158481  0.000000e+00        0.0        0.0        1.0         0.0
130757   4.083565e-11        2.0        0.0        1.0         0.0
596789   0.000000e+00        1.0        0.0        1.0         0.0
33774    0.000000e+00        1.0        0.0        1.0         0.0
...               ...        ...        ...        ...         ...
1147044  0.000000e+00        0.0        0.0        1.0         0.0
1026102  1.020891e-10        2.0        0.0        1.0         0.0
862968   6.326485e-05        6.0        0.0        1.0         0.0
1347712  0.000000e+00        1.0        0.0        1.0         0.0
465231   6.374377e-05        3.0        0.0        1.0         0.0

[1082352 rows x 5 columns]


In [11]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [12]:
print(X_train[47])

[-0.01065837 -0.00267066 -0.1957803   0.20262383 -0.00182844]


In [13]:
len(X_train)

1082352

In [14]:
xgb_model_improved = xgb.XGBClassifier(
    objective='binary:logistic',  
    eval_metric='aucpr',  
    n_estimators=1,  
    gamma=0,
    learning_rate=0.1,
    max_depth=3,
    reg_lambda=1,
    scale_pos_weight=0.3,
    subsample=0.9,
    colsample_bytree=0.5
)

start_time = time.time()

xgb_model_improved.fit(
    X_train, y_train,
    eval_set=[(X_test, y_test)],  
    verbose=True
)

end_time = time.time()
print(f"Training time: {end_time - start_time:.4f} seconds")

[0]	validation_0-aucpr:0.95913
Training time: 0.2204 seconds


In [32]:
import numpy as np


for i, sample in enumerate(X_train):
    sample_array = sample.reshape(1, -1)
    pred = xgb_model_improved.predict(sample_array)[0]
    if pred == 0:
        print("Benign sample found at index:", i)
        print("Sample:", sample)
        break


Benign sample found at index: 77
Sample: [ 0.04906161 -0.00264652 -0.1957803   0.20262383 -0.00182844]


In [28]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix, classification_report

y_pred_probs = xgb_model_improved.predict_proba(X_test)[:, 1]
y_pred = (y_pred_probs >= 0.5).astype(int)  

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
roc_auc = roc_auc_score(y_test, y_pred_probs)
conf_matrix = confusion_matrix(y_test, y_pred)

print(f"Accuracy     : {accuracy:.4f}")
print(f"Precision    : {precision:.4f}")
print(f"Recall       : {recall:.4f}")
print(f"F1 Score     : {f1:.4f}")
print(f"ROC-AUC Score: {roc_auc:.4f}")
print("\nConfusion Matrix:")
print(conf_matrix)

print("\nClassification Report:")
print(classification_report(y_test, y_pred))


Accuracy     : 0.9337
Precision    : 0.9318
Recall       : 0.9961
F1 Score     : 0.9629
ROC-AUC Score: 0.8707

Confusion Matrix:
[[ 26622  22697]
 [  1213 310253]]

Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.54      0.69     49319
           1       0.93      1.00      0.96    311466

    accuracy                           0.93    360785
   macro avg       0.94      0.77      0.83    360785
weighted avg       0.94      0.93      0.93    360785



In [16]:
import joblib
import os

model_filename = 'xgb_model_improved.pkl'
joblib.dump(xgb_model_improved, model_filename)

model_size_bytes = os.path.getsize(model_filename)
model_size_kb = model_size_bytes / 1024
model_size_mb = model_size_kb / 1024

print(f"Model size: {model_size_kb:.2f} KB")
print(f"Model size: {model_size_mb:.2f} MB")




Model size: 24.05 KB
Model size: 0.02 MB


In [16]:
X_test_10x = np.concatenate([X_test] * 10, axis=0)

In [17]:


inference_start = time.time()
y_pred = xgb_model_improved.predict(X_test_10x)
inference_end = time.time()

print(f"Inference time: {inference_end - inference_start:.4f} seconds")


Inference time: 0.0603 seconds


In [18]:




nb_model = GaussianNB(var_smoothing=1e-9)

start_time = time.time()
nb_model.fit(X_train, y_train)
end_time = time.time()

training_time = end_time - start_time




print(f"Training Time: {training_time:.4f} seconds")


Training Time: 0.1126 seconds


In [29]:
y_pred = nb_model.predict(X_test)
y_pred_proba = nb_model.predict_proba(X_test)[:, 1]  

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
roc_auc = roc_auc_score(y_test, y_pred_proba)

print(f"\n🧠 Naïve Bayes Model Evaluation:")
print(f"Training Time : {training_time:.4f} seconds")
print(f"Accuracy      : {accuracy:.4f}")
print(f"Precision     : {precision:.4f}")
print(f"Recall        : {recall:.4f}")
print(f"F1 Score      : {f1:.4f}")
print(f"ROC-AUC Score : {roc_auc:.4f}")
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

model_filename = "nb_model.pkl"
joblib.dump(nb_model, model_filename)
model_size_bytes = os.path.getsize(model_filename)
print(f"\nModel Size    : {model_size_bytes / 1024:.2f} KB")

# 6. Delete the model file
os.remove(model_filename)
print("Model file deleted ✅")


🧠 Naïve Bayes Model Evaluation:
Training Time : 0.1189 seconds
Accuracy      : 0.9026
Precision     : 0.8986
Recall        : 1.0000
F1 Score      : 0.9466
ROC-AUC Score : 0.5061

Confusion Matrix:
[[ 14174  35145]
 [     2 311464]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.29      0.45     49319
           1       0.90      1.00      0.95    311466

    accuracy                           0.90    360785
   macro avg       0.95      0.64      0.70    360785
weighted avg       0.91      0.90      0.88    360785


Model Size    : 0.91 KB
Model file deleted ✅


In [21]:
inference_start = time.time()
y_pred = nb_model.predict(X_test_10x)
inference_end = time.time()

print(f"Inference time: {inference_end - inference_start:.4f} seconds")

Inference time: 0.2797 seconds


In [50]:
X_train=X_train[:357000]
y_train=y_train[:357000]
print(len(X_train))
print(len(X_test))

357000
360785


In [52]:
xgb_model_improved = xgb.XGBClassifier(
    objective='binary:logistic',  
    eval_metric='aucpr',  
    n_estimators=1,  
    gamma=0,
    learning_rate=0.1,
    max_depth=3,
    reg_lambda=1,
    scale_pos_weight=0.3,
    subsample=0.9,
    colsample_bytree=0.5
)

start_time = time.time()

xgb_model_improved.fit(
    X_train, y_train,
    eval_set=[(X_test, y_test)],  
    verbose=True
)

end_time = time.time()
print(f"Training time: {end_time - start_time:.4f} seconds")

[0]	validation_0-aucpr:0.47624
Training time: 0.2084 seconds


In [54]:


inference_start = time.time()
y_pred = xgb_model_improved.predict(X_test)
inference_end = time.time()

print(f"Inference time: {inference_end - inference_start:.4f} seconds")


Inference time: 0.0455 seconds


In [56]:




nb_model = GaussianNB(var_smoothing=1e-9)

start_time = time.time()
nb_model.fit(X_train, y_train)
end_time = time.time()

training_time = end_time - start_time




print(f"Training Time: {training_time:.4f} seconds")


Training Time: 0.0441 seconds


In [59]:
inference_start = time.time()
y_pred = nb_model.predict(X_test)
inference_end = time.time()

print(f"Inference time: {inference_end - inference_start:.4f} seconds")

Inference time: 0.0608 seconds


In [60]:
X_train=X_train[:35000]
y_train=y_train[:35000]
X_test=X_test[:35000]
y_test=y_test[:35000]
print(len(X_test))

35000


In [61]:
len(X_train)

35000

In [63]:
import time

In [65]:

xgb_model_improved = xgb.XGBClassifier(
    objective='binary:logistic',  
    eval_metric='aucpr', 
    n_estimators=1,  
    gamma=0,
    learning_rate=0.1,
    max_depth=3,
    reg_lambda=1,
    scale_pos_weight=0.3,
    subsample=0.9,
    colsample_bytree=0.5
)

start_time = time.time()

xgb_model_improved.fit(
    X_train, y_train,
    eval_set=[(X_test, y_test)],  
    verbose=True
)

end_time = time.time()
print(f"Training time: {end_time - start_time:.4f} seconds")

[0]	validation_0-aucpr:0.47119
Training time: 0.0500 seconds


In [68]:


inference_start = time.time()
y_pred = xgb_model_improved.predict(X_test)
inference_end = time.time()

print(f"Inference time: {inference_end - inference_start:.4f} seconds")


Inference time: 0.0167 seconds


In [74]:
inference_start = time.time()
y_pred = nb_model.predict(X_test)
inference_end = time.time()

print(f"Inference time: {inference_end - inference_start:.4f} seconds")

Inference time: 0.0068 seconds
